name: "Nix Flake Check"

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Run Nix Flake Check
        run: nix flake check 
